export const images: { [k: string]: any } = {
  LogoDark: require('../assets/dfox_dark.png'),
  LogoLight: require('../assets/dfox_light.png'),
  discord: require('../assets/discord-icon.png'),
  google: require('../assets/google-icon.png'),
  CFalcon: require('../assets/characters/CFalcon.png'),
  Doc: require('../assets/characters/Doc.png'),
  Bowser: require('../assets/characters/Bowser.png'),
  'Donkey Kong': require('../assets/characters/Donkey Kong.png'),
  Falco: require('../assets/characters/Falco.png'),
  Fox: require('../assets/characters/Fox.png'),
  Ganondorf: require('../assets/characters/Ganondorf.png'),
  GnW: require('../assets/characters/GnW.png'),
  Icies: require('../assets/characters/Icies.png'),
  Kirby: require('../assets/characters/Kirby.png'),
  Link: require('../assets/characters/Link.png'),
  Luigi: require('../assets/characters/Luigi.png'),
  Mario: require('../assets/characters/Mario.png'),
  Marth: require('../assets/characters/Marth.png'),
  Mewtwo: require('../assets/characters/Mewtwo.png'),
  Ness: require('../assets/characters/Ness.png'),
  Peach: require('../assets/characters/Peach.png'),
  Pichu: require('../assets/characters/Pichu.png'),
  Pikachu: require('../assets/characters/Pikachu.png'),
  Puff: require('../assets/characters/Puff.png'),
  Roy: require('../assets/characters/Roy.png'),
  Samus: require('../assets/characters/Samus.png'),
  Sheik: require('../assets/characters/Sheik.png'),
  YL: require('../assets/characters/YL.png'),
  Zelda: require('../assets/characters/Zelda.png'),
  Yoshi: require('../assets/characters/Yoshi.png'),
};
