create table "public"."Bookmarked Lessons" (
    "userId" uuid not null,
    "lessonId" bigint not null,
    "id" bigint generated by default as identity not null
);


alter table "public"."Bookmarked Lessons" enable row level security;

create table "public"."Lessons" (
    "id" bigint generated by default as identity not null,
    "player" text not null,
    "character" text not null,
    "opponent" text not null,
    "date" date not null,
    "link" text not null,
    "timestamped" boolean not null,
    "notes" text
);


alter table "public"."Lessons" enable row level security;

create table "public"."New Uploads" (
    "id" bigint generated by default as identity not null,
    "lessonId" bigint not null
);


alter table "public"."New Uploads" enable row level security;

create table "public"."Recently Viewed" (
    "userId" uuid not null,
    "lessonId" bigint not null,
    "createdAt" timestamp without time zone default now(),
    "id" bigint generated by default as identity not null
);


alter table "public"."Recently Viewed" enable row level security;

create table "public"."Watched Lessons" (
    "userId" uuid not null,
    "lessonId" bigint not null,
    "id" bigint generated by default as identity not null
);


alter table "public"."Watched Lessons" enable row level security;

CREATE UNIQUE INDEX "Bookmarked Lessons_id_key" ON public."Bookmarked Lessons" USING btree (id);

CREATE UNIQUE INDEX "Bookmarked Lessons_pkey" ON public."Bookmarked Lessons" USING btree (id);

CREATE UNIQUE INDEX "Lessons_link_key" ON public."Lessons" USING btree (link);

CREATE UNIQUE INDEX "Lessons_pkey" ON public."Lessons" USING btree (id);

CREATE UNIQUE INDEX "New Uploads_id_key" ON public."New Uploads" USING btree (id);

CREATE UNIQUE INDEX "New Uploads_lessonId_key" ON public."New Uploads" USING btree ("lessonId");

CREATE UNIQUE INDEX "New Uploads_pkey" ON public."New Uploads" USING btree (id);

CREATE UNIQUE INDEX "Recently Viewed_id_key" ON public."Recently Viewed" USING btree (id);

CREATE UNIQUE INDEX "Recently Viewed_pkey" ON public."Recently Viewed" USING btree (id);

CREATE UNIQUE INDEX "Watched Lessons_id_key" ON public."Watched Lessons" USING btree (id);

CREATE UNIQUE INDEX "Watched Lessons_pkey" ON public."Watched Lessons" USING btree (id);

alter table "public"."Bookmarked Lessons" add constraint "Bookmarked Lessons_pkey" PRIMARY KEY using index "Bookmarked Lessons_pkey";

alter table "public"."Lessons" add constraint "Lessons_pkey" PRIMARY KEY using index "Lessons_pkey";

alter table "public"."New Uploads" add constraint "New Uploads_pkey" PRIMARY KEY using index "New Uploads_pkey";

alter table "public"."Recently Viewed" add constraint "Recently Viewed_pkey" PRIMARY KEY using index "Recently Viewed_pkey";

alter table "public"."Watched Lessons" add constraint "Watched Lessons_pkey" PRIMARY KEY using index "Watched Lessons_pkey";

alter table "public"."Bookmarked Lessons" add constraint "Bookmarked Lessons_id_key" UNIQUE using index "Bookmarked Lessons_id_key";

alter table "public"."Bookmarked Lessons" add constraint "Bookmarked Lessons_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lessons"(id) not valid;

alter table "public"."Bookmarked Lessons" validate constraint "Bookmarked Lessons_lessonId_fkey";

alter table "public"."Bookmarked Lessons" add constraint "Bookmarked Lessons_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."Bookmarked Lessons" validate constraint "Bookmarked Lessons_userId_fkey";

alter table "public"."Lessons" add constraint "Lessons_link_key" UNIQUE using index "Lessons_link_key";

alter table "public"."New Uploads" add constraint "New Uploads_id_key" UNIQUE using index "New Uploads_id_key";

alter table "public"."New Uploads" add constraint "New Uploads_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lessons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."New Uploads" validate constraint "New Uploads_lessonId_fkey";

alter table "public"."New Uploads" add constraint "New Uploads_lessonId_key" UNIQUE using index "New Uploads_lessonId_key";

alter table "public"."Recently Viewed" add constraint "Recently Viewed_id_key" UNIQUE using index "Recently Viewed_id_key";

alter table "public"."Recently Viewed" add constraint "Recently Viewed_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lessons"(id) not valid;

alter table "public"."Recently Viewed" validate constraint "Recently Viewed_lessonId_fkey";

alter table "public"."Recently Viewed" add constraint "Recently Viewed_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Recently Viewed" validate constraint "Recently Viewed_userId_fkey";

alter table "public"."Watched Lessons" add constraint "Watched Lessons_id_key" UNIQUE using index "Watched Lessons_id_key";

alter table "public"."Watched Lessons" add constraint "Watched Lessons_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lessons"(id) not valid;

alter table "public"."Watched Lessons" validate constraint "Watched Lessons_lessonId_fkey";

alter table "public"."Watched Lessons" add constraint "Watched Lessons_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Watched Lessons" validate constraint "Watched Lessons_userId_fkey";

grant delete on table "public"."Bookmarked Lessons" to "anon";

grant insert on table "public"."Bookmarked Lessons" to "anon";

grant references on table "public"."Bookmarked Lessons" to "anon";

grant select on table "public"."Bookmarked Lessons" to "anon";

grant trigger on table "public"."Bookmarked Lessons" to "anon";

grant truncate on table "public"."Bookmarked Lessons" to "anon";

grant update on table "public"."Bookmarked Lessons" to "anon";

grant delete on table "public"."Bookmarked Lessons" to "authenticated";

grant insert on table "public"."Bookmarked Lessons" to "authenticated";

grant references on table "public"."Bookmarked Lessons" to "authenticated";

grant select on table "public"."Bookmarked Lessons" to "authenticated";

grant trigger on table "public"."Bookmarked Lessons" to "authenticated";

grant truncate on table "public"."Bookmarked Lessons" to "authenticated";

grant update on table "public"."Bookmarked Lessons" to "authenticated";

grant delete on table "public"."Bookmarked Lessons" to "service_role";

grant insert on table "public"."Bookmarked Lessons" to "service_role";

grant references on table "public"."Bookmarked Lessons" to "service_role";

grant select on table "public"."Bookmarked Lessons" to "service_role";

grant trigger on table "public"."Bookmarked Lessons" to "service_role";

grant truncate on table "public"."Bookmarked Lessons" to "service_role";

grant update on table "public"."Bookmarked Lessons" to "service_role";

grant delete on table "public"."Lessons" to "anon";

grant insert on table "public"."Lessons" to "anon";

grant references on table "public"."Lessons" to "anon";

grant select on table "public"."Lessons" to "anon";

grant trigger on table "public"."Lessons" to "anon";

grant truncate on table "public"."Lessons" to "anon";

grant update on table "public"."Lessons" to "anon";

grant delete on table "public"."Lessons" to "authenticated";

grant insert on table "public"."Lessons" to "authenticated";

grant references on table "public"."Lessons" to "authenticated";

grant select on table "public"."Lessons" to "authenticated";

grant trigger on table "public"."Lessons" to "authenticated";

grant truncate on table "public"."Lessons" to "authenticated";

grant update on table "public"."Lessons" to "authenticated";

grant delete on table "public"."Lessons" to "service_role";

grant insert on table "public"."Lessons" to "service_role";

grant references on table "public"."Lessons" to "service_role";

grant select on table "public"."Lessons" to "service_role";

grant trigger on table "public"."Lessons" to "service_role";

grant truncate on table "public"."Lessons" to "service_role";

grant update on table "public"."Lessons" to "service_role";

grant delete on table "public"."New Uploads" to "anon";

grant insert on table "public"."New Uploads" to "anon";

grant references on table "public"."New Uploads" to "anon";

grant select on table "public"."New Uploads" to "anon";

grant trigger on table "public"."New Uploads" to "anon";

grant truncate on table "public"."New Uploads" to "anon";

grant update on table "public"."New Uploads" to "anon";

grant delete on table "public"."New Uploads" to "authenticated";

grant insert on table "public"."New Uploads" to "authenticated";

grant references on table "public"."New Uploads" to "authenticated";

grant select on table "public"."New Uploads" to "authenticated";

grant trigger on table "public"."New Uploads" to "authenticated";

grant truncate on table "public"."New Uploads" to "authenticated";

grant update on table "public"."New Uploads" to "authenticated";

grant delete on table "public"."New Uploads" to "service_role";

grant insert on table "public"."New Uploads" to "service_role";

grant references on table "public"."New Uploads" to "service_role";

grant select on table "public"."New Uploads" to "service_role";

grant trigger on table "public"."New Uploads" to "service_role";

grant truncate on table "public"."New Uploads" to "service_role";

grant update on table "public"."New Uploads" to "service_role";

grant delete on table "public"."Recently Viewed" to "anon";

grant insert on table "public"."Recently Viewed" to "anon";

grant references on table "public"."Recently Viewed" to "anon";

grant select on table "public"."Recently Viewed" to "anon";

grant trigger on table "public"."Recently Viewed" to "anon";

grant truncate on table "public"."Recently Viewed" to "anon";

grant update on table "public"."Recently Viewed" to "anon";

grant delete on table "public"."Recently Viewed" to "authenticated";

grant insert on table "public"."Recently Viewed" to "authenticated";

grant references on table "public"."Recently Viewed" to "authenticated";

grant select on table "public"."Recently Viewed" to "authenticated";

grant trigger on table "public"."Recently Viewed" to "authenticated";

grant truncate on table "public"."Recently Viewed" to "authenticated";

grant update on table "public"."Recently Viewed" to "authenticated";

grant delete on table "public"."Recently Viewed" to "service_role";

grant insert on table "public"."Recently Viewed" to "service_role";

grant references on table "public"."Recently Viewed" to "service_role";

grant select on table "public"."Recently Viewed" to "service_role";

grant trigger on table "public"."Recently Viewed" to "service_role";

grant truncate on table "public"."Recently Viewed" to "service_role";

grant update on table "public"."Recently Viewed" to "service_role";

grant delete on table "public"."Watched Lessons" to "anon";

grant insert on table "public"."Watched Lessons" to "anon";

grant references on table "public"."Watched Lessons" to "anon";

grant select on table "public"."Watched Lessons" to "anon";

grant trigger on table "public"."Watched Lessons" to "anon";

grant truncate on table "public"."Watched Lessons" to "anon";

grant update on table "public"."Watched Lessons" to "anon";

grant delete on table "public"."Watched Lessons" to "authenticated";

grant insert on table "public"."Watched Lessons" to "authenticated";

grant references on table "public"."Watched Lessons" to "authenticated";

grant select on table "public"."Watched Lessons" to "authenticated";

grant trigger on table "public"."Watched Lessons" to "authenticated";

grant truncate on table "public"."Watched Lessons" to "authenticated";

grant update on table "public"."Watched Lessons" to "authenticated";

grant delete on table "public"."Watched Lessons" to "service_role";

grant insert on table "public"."Watched Lessons" to "service_role";

grant references on table "public"."Watched Lessons" to "service_role";

grant select on table "public"."Watched Lessons" to "service_role";

grant trigger on table "public"."Watched Lessons" to "service_role";

grant truncate on table "public"."Watched Lessons" to "service_role";

grant update on table "public"."Watched Lessons" to "service_role";

create policy "Enable delete for users based on user_id"
on "public"."Bookmarked Lessons"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable insert for users based on user_id"
on "public"."Bookmarked Lessons"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable read access for individual users"
on "public"."Bookmarked Lessons"
as permissive
for select
to public
using ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable read access for all users"
on "public"."Lessons"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."New Uploads"
as permissive
for select
to public
using (true);


create policy "Enable delete for users based on user_id"
on "public"."Recently Viewed"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable insert for users based on user_id"
on "public"."Recently Viewed"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable read access for all users"
on "public"."Recently Viewed"
as permissive
for select
to public
using ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable delete for users based on user_id"
on "public"."Watched Lessons"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable insert for users based on user_id"
on "public"."Watched Lessons"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = "userId"));


create policy "Enable read access for all users"
on "public"."Watched Lessons"
as permissive
for select
to public
using ((( SELECT auth.uid() AS uid) = "userId"));



